-- MySQL Script generated by MySQL Workbench
-- Wed Jun  8 16:10:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Jarvis
-- -----------------------------------------------------
-- Jarvis as MCD given 07062022

-- -----------------------------------------------------
-- Schema Jarvis
--
-- Jarvis as MCD given 07062022
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Jarvis` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `Jarvis` ;

-- -----------------------------------------------------
-- Table `Jarvis`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`utilisateur` (
  `id_u` INT NOT NULL AUTO_INCREMENT,
  `prenom_u` VARCHAR(45) NOT NULL,
  `nom_u` VARCHAR(45) NOT NULL,
  `date_de_naissance` DATE NOT NULL,
  `email_u` VARCHAR(45) NOT NULL,
  `Sexe` VARCHAR(1) NOT NULL,
  `mdp_u` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_u`),
  UNIQUE INDEX `id_u_UNIQUE` (`id_u` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jarvis`.`membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`membre` (
  `id_m` INT NOT NULL AUTO_INCREMENT,
  `lien_parent` VARCHAR(45) NOT NULL,
  `utilisateur_id_u` INT NOT NULL,
  UNIQUE INDEX `id_m_UNIQUE` (`id_m` ASC),
  PRIMARY KEY (`id_m`, `utilisateur_id_u`),
  INDEX `fk_membre_utilisateur_idx` (`utilisateur_id_u` ASC),
  CONSTRAINT `fk_membre_utilisateur`
    FOREIGN KEY (`utilisateur_id_u`)
    REFERENCES `Jarvis`.`utilisateur` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jarvis`.`co-propriétaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`co-propriétaire` (
  `id_co-pro` INT NOT NULL AUTO_INCREMENT,
  `utilisateur_id_u` INT NOT NULL,
  UNIQUE INDEX `id_co-pro_UNIQUE` (`id_co-pro` ASC),
  PRIMARY KEY (`id_co-pro`, `utilisateur_id_u`),
  INDEX `fk_co-propriétaire_utilisateur1_idx` (`utilisateur_id_u` ASC),
  CONSTRAINT `fk_co-propriétaire_utilisateur1`
    FOREIGN KEY (`utilisateur_id_u`)
    REFERENCES `Jarvis`.`utilisateur` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jarvis`.`Propriétaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`Propriétaire` (
  `id_pro` INT NOT NULL AUTO_INCREMENT,
  `utilisateur_id_u` INT NOT NULL,
  UNIQUE INDEX `id_pro_UNIQUE` (`id_pro` ASC),
  PRIMARY KEY (`id_pro`, `utilisateur_id_u`),
  INDEX `fk_Propriétaire_utilisateur1_idx` (`utilisateur_id_u` ASC),
  CONSTRAINT `fk_Propriétaire_utilisateur1`
    FOREIGN KEY (`utilisateur_id_u`)
    REFERENCES `Jarvis`.`utilisateur` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jarvis`.`Domicile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`Domicile` (
  `id_domicile` INT NOT NULL AUTO_INCREMENT,
  `annee_construction` INT NOT NULL,
  `superficie` VARCHAR(5) NOT NULL,
  `Propriétaire_id_pro` INT NOT NULL,
  `Propriétaire_utilisateur_id_u` INT NOT NULL,
  PRIMARY KEY (`id_domicile`, `Propriétaire_id_pro`, `Propriétaire_utilisateur_id_u`),
  UNIQUE INDEX `id_domicile_UNIQUE` (`id_domicile` ASC),
  INDEX `fk_Domicile_Propriétaire1_idx` (`Propriétaire_id_pro` ASC, `Propriétaire_utilisateur_id_u` ASC),
  CONSTRAINT `fk_Domicile_Propriétaire1`
    FOREIGN KEY (`Propriétaire_id_pro` , `Propriétaire_utilisateur_id_u`)
    REFERENCES `Jarvis`.`Propriétaire` (`id_pro` , `utilisateur_id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jarvis`.`Piece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`Piece` (
  `id_piece` INT NOT NULL AUTO_INCREMENT,
  `nom_piece` VARCHAR(45) NOT NULL,
  `Domicile_id_domicile` INT NOT NULL,
  UNIQUE INDEX `idPiece_UNIQUE` (`id_piece` ASC),
  PRIMARY KEY (`id_piece`, `Domicile_id_domicile`),
  INDEX `fk_Piece_Domicile1_idx` (`Domicile_id_domicile` ASC),
  CONSTRAINT `fk_Piece_Domicile1`
    FOREIGN KEY (`Domicile_id_domicile`)
    REFERENCES `Jarvis`.`Domicile` (`id_domicile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jarvis`.`Appareils`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`Appareils` (
  `id_appareil` INT NOT NULL AUTO_INCREMENT,
  `nom_appareil` VARCHAR(45) NOT NULL,
  `type_appareil` VARCHAR(45) NOT NULL,
  `Piece_id_piece` INT NOT NULL,
  UNIQUE INDEX `id_appareil_UNIQUE` (`id_appareil` ASC),
  PRIMARY KEY (`id_appareil`, `Piece_id_piece`),
  INDEX `fk_Appareils_Piece1_idx` (`Piece_id_piece` ASC),
  CONSTRAINT `fk_Appareils_Piece1`
    FOREIGN KEY (`Piece_id_piece`)
    REFERENCES `Jarvis`.`Piece` (`id_piece`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jarvis`.`invite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`invite` (
  `Propriétaire_id_pro` INT NOT NULL,
  `utilisateur_id_u` INT NOT NULL,
  PRIMARY KEY (`Propriétaire_id_pro`, `utilisateur_id_u`),
  INDEX `fk_Propriétaire_has_utilisateur_utilisateur1_idx` (`utilisateur_id_u` ASC),
  INDEX `fk_Propriétaire_has_utilisateur_Propriétaire1_idx` (`Propriétaire_id_pro` ASC),
  CONSTRAINT `fk_Propriétaire_has_utilisateur_Propriétaire1`
    FOREIGN KEY (`Propriétaire_id_pro`)
    REFERENCES `Jarvis`.`Propriétaire` (`id_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Propriétaire_has_utilisateur_utilisateur1`
    FOREIGN KEY (`utilisateur_id_u`)
    REFERENCES `Jarvis`.`utilisateur` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jarvis`.`contenir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jarvis`.`contenir` (
  `Domicile_id_domicile` INT NOT NULL,
  `utilisateur_id_u` INT NOT NULL,
  PRIMARY KEY (`Domicile_id_domicile`, `utilisateur_id_u`),
  INDEX `fk_Domicile_has_utilisateur_utilisateur1_idx` (`utilisateur_id_u` ASC),
  INDEX `fk_Domicile_has_utilisateur_Domicile1_idx` (`Domicile_id_domicile` ASC),
  CONSTRAINT `fk_Domicile_has_utilisateur_Domicile1`
    FOREIGN KEY (`Domicile_id_domicile`)
    REFERENCES `Jarvis`.`Domicile` (`id_domicile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Domicile_has_utilisateur_utilisateur1`
    FOREIGN KEY (`utilisateur_id_u`)
    REFERENCES `Jarvis`.`utilisateur` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
